[package]
name = "roblox"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
detour = { git = "https://github.com/Hpmason/detour-rs", branch = "fix-nightly1.67.0-changes" }
egui = "0.19"
egui-d3d11 = "0.8"
egui-notify = "0.4"
log = "0.4"
pelite = "0.10"
shroud = { version = "*", features = ["directx11"] }

[dependencies.windows]
version = "0.36"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]
